### ISSUE TITLE
Mining 

### ISSUE THREAD

**Issue by JordanMartinez991** [Monolith-RP/issues#191] opened 2021-11-04 13:17 UTC
### Describe The Bug

The bug is when u hit a mining rock when u get it too 0 percent it doesn't regain heath 

### Expected Behavior

not being able too mine anymore 

### Additional Context

no

**Comment by RedSpeeds** [comment] 2021-11-04 13:20
Cannot reproduce

**Comment by DevulTj** [comment] 2021-11-09 13:32
Should be fixed.

**Closed as completed by DevulTj** 2021-11-09 13:32 UTC
Labels: bug, unconfirmed
