### ISSUE TITLE
Send out chat message when a users opens their glovebox/trunk

### ISSUE THREAD

**Issue by RedSpeeds** [Monolith-RP/issues#182] opened 2021-11-01 12:27 UTC
### Describe The Feature

Put a action message into the chat when a user opens their glovebox/trunk

### Why Would You Like This Feature?

At the moment its completely possible for users to access their trunk and glovebox silently this would allow them to stash illegal items unnoticed.

Say im doing a traffic stop and this guy has a M4 on him he would be able to open the glovebox stash the weapon and i would never ever know.

Now lets say there is a action message as im walking over a action message alerts me to him opening his glovebox this would allow me to search the car on probable cause allowing me to find the illegal item (Requires #178 )

**Comment by JacubRSTNC** [comment] 2021-11-02 14:58
Isn't this an alternative suggestion to #177

**Comment by DevulTj** [comment] 2021-11-05 11:16
Yes, this is a duplicate of #177

**Closed as completed by DevulTj** 2021-11-05 11:16 UTC
Labels: feature, unconfirmed
