### ISSUE TITLE
Ambulance spawn borked

### ISSUE THREAD

**Issue by Its-Valentino** [Monolith-RP/issues#198] opened 2021-11-07 02:36 UTC
### Describe The Bug

If you spawn in an ambulance at the secondary spawn location it gets stuck inside the wall and you're unable to store it again or get it out.

### To Reproduce

1. Go to hospital
2. Spawn an ambulance while one is already in the primary spawn location

### Expected Behavior

Spawned vehicle doesn't get stuck inside wall

**Comment by aaddaammgg** [comment] 2021-11-07 02:39
Duplicate of #188

**Comment by Its-Valentino** [comment] 2021-11-07 02:42
> Duplicate of #188

oops sorry

**Closed as completed** 2021-11-09 17:19 UTC
Labels: bug, unconfirmed
